package com.jspider.metier.responseParser.model;

public enum ElementParserTools {
	// HTML
	GET_ELEMENT_BY_INDEX,

	GET_CHILDREN,

	GET_ELEMENT_BY_ID, GET_ELEMENT_BY_CLASS, GET_ELEMENT_BY_TAG, GET_ELEMENT_BY_SELECTOR,

	GET_ATTR,

	GET_VAL, VAL_COMPUTING, GET_CHILDREN_VALS, GET_DATE, ELEMENT_COMPUTING,

	GET_VAL_REGEX,

	// JSON
	GET_JSONOBJECT_BY_NAME, GET_STRING_BY_NAME, GET_JSON_INT_BY_NAME,

	// OTHERS
	CONSTANT, ELEMENT;
}
